---
_build_dir: "{{ build_dir | default('/tmp') }}"

_canonical_hostname: "{{ canonical_hostname | default('localhost') }}"
_irods_zone_name: "{{ irods_zone_name | default('tempZone') }}"

_webdav_allowed_src: "{{ webdav_allowed_src | default(['0.0.0.0/0']) }}"
_webdav_auth_name: "{{ webdav_auth_name | default('CyVerse') }}"
_webdav_max_request_workers: "{{ webdav_max_request_workers | default(192) }}"
_webdav_server_limit: "{{ webdav_server_limit | default(48) }}"
_webdav_threads_per_child: "{{ webdav_threads_per_child | default(4) }}"
_webdav_tls_cert_file: "{{ webdav_tls_cert_file | default('/etc/ssl/certs/dummy.crt') }}"
_webdav_tls_chain_file: "{{ webdav_tls_chain_file | default('/etc/ssl/certs/dummy-chain.crt') }}"
_webdav_tls_key_file: "{{ webdav_tls_key_file | default('/etc/ssl/certs/dummy.key') }}"

_webdav_local_irods_vault_project_path: "{{ webdav_local_irods_vault_project_path | default('/irods_vault') }}"
