---
# VARIABLES
#  svc  the base resource for html documents

- name: create {{ svc }}/ subdirectories
  file:
    path: /var/www/html/{{ svc }}/{{ _irods_zone_name }}/commons
    recurse: true
    state: directory

- name: add templated content for /{{ svc }}/
  template:
    src: templates/webdav/var/{{ item.src }}
    dest: /var/www/html/{{ svc }}/{{ item.dest }}
    owner: apache
    mode: u+r
  with_items:
    - src: index.html.j2
      dest: index.html
    - src: zone-index.html.j2
      dest: "{{ _irods_zone_name }}/index.html"
    - src: commons-index.html.j2
      dest: "{{ _irods_zone_name }}/commons/index.html"
