---
- name: Install and configure apache
  hosts: webdav
  become: true
  collections:
    - community.general
  roles:
    - role: geerlingguy.apache
      vars:
        apache_ssl_cipher_suite: "HIGH:3DES:!aNULL:!MD5:!SEED:!IDEA"
        apache_global_vhost_settings: |
          <IfModule !log_forensic_module>
            LoadModule log_forensic_module modules/mod_log_forensic.so
          </IfModule>

          <IfModule !proxy_html_module>
            LoadModule proxy_html_module modules/mod_proxy_html.so
          </IfModule>

          <IfModule !sed_module>
            LoadModule sed_module modules/mod_sed.so
          </IfModule>

          <IfModule !unique_id_module>
            LoadModule unique_id_module modules/mod_unique_id.so
          </IfModule>

          <IfModule !mpm_worker_module>
            LoadModule mpm_worker_module modules/mod_mpm_worker.so
          </IfModule>

          <IfModule !authnz_ldap_module>
            LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
          </IfModule>

          <IfModule !ldap_module>
            LoadModule ldap_module modules/mod_ldap.so
          </IfModule>

          ForensicLog logs/forensic_log
          ErrorLogFormat "%{cu}t %-L [pid %P] [%-m:%l] %-a %E: %M"

          Listen 443 https
          Listen 8047

          SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
          SSLRandomSeed connect builtin
          SSLRandomSeed startup file:/dev/urandom 256
          SSLSessionCache shmcb:/run/httpd/sslcache(512000)

          ProxyErrorOverride On
          ProxyHTMLEnable On
          ProxyHTMLLinks a href
          ProxyHTMLLinks base href

          ServerLimit {{ _webdav_server_limit }}
          ThreadsPerChild {{ _webdav_threads_per_child }}
          MaxRequestWorkers {{ _webdav_max_request_workers }}

          LDAPSharedCacheSize 500000
          LDAPCacheEntries 1024
          LDAPCacheTTL 600
          LDAPOpCacheEntries 1024
          LDAPOpCacheTTL 600

        apache_vhosts:
          - servername: "{{ _canonical_hostname }}"
            listen_ip: 127.0.0.1
            listen_port: 8047
            extra_parameters: |
              DocumentRoot {{ _webdav_local_irods_vault_project_path }}              
              <Directory {{ _webdav_local_irods_vault_project_path }}>
                Require all granted
                AllowOverride All
                Options +Indexes

                AuthName {{ _webdav_auth_name }}
                AuthType Basic
                AuthBasicProvider ldap
                AuthLDAPURL "ldap://127.0.0.1/dc=iplantcollaborative,dc=org?uid?one"
                Require valid-user
              </Directory>

              ErrorLog logs/error_log
              CustomLog logs/access_log {{ '"%{%Y-%m-%d %T}t.%{usec_frac}t %{X-Forwarded-For}i \"%r\" %>s %L %{forensic-id}n"' }}
              LogLevel warn

              Header set Access-Control-Allow-Headers "Range"
              Header set Access-Control-Allow-Methods "GET, HEAD, OPTIONS"
              Header set Access-Control-Allow-Origin "*"

              UseCanonicalName On

              RewriteEngine On
              RewriteCond %{REQUEST_METHOD} ^(PUT|POST|DELETE)
              RewriteRule .* - [F]
            comment: Vhost for accessing Local iRODS Resource Server's content
            locations:
              - path: /
                comment: Read access to some project folders stored in local file system

          - servername: "{{ _canonical_hostname }}"
            listen_ip: 127.0.0.1
            extra_parameters: |
              ErrorLog logs/error_log
              CustomLog logs/access_log {{ '"%{%Y-%m-%d %T}t.%{usec_frac}t %{X-Forwarded-For}i \"%r\" %>s %L %{forensic-id}n"' }}
              LogLevel warn

              Header set Access-Control-Allow-Headers "Range"
              Header set Access-Control-Allow-Methods "GET, HEAD, OPTIONS"
              Header set Access-Control-Allow-Origin "*"

              UseCanonicalName On
              RewriteEngine On
              
              # Add trailing slash
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects$ /dav/{{ _irods_zone_name }}/projects/ [R=308,L]
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects/eht$ /dav/{{ _irods_zone_name }}/projects/eht/ [R=308,L]
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects/bhpire$ /dav/{{ _irods_zone_name }}/projects/bhpire/ [R=308,L]
              

              # Redirect read (GET and HEAD) access to local iRODS resource server's data 
              RewriteCond %{REQUEST_METHOD} ^(GET|HEAD)
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects/eht/(.*)$ http://127.0.0.1:8047/eht/$1 [P,L]
              RewriteCond %{REQUEST_METHOD} ^(GET|HEAD)
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects/bhpire/(.*)$ http://127.0.0.1:8047/bhpire/$1 [P,L]
              
              SSLProxyEngine on
              # directory listing on projects root directory should be proxied to data.cyverse.org as users can move to eht or bhpire subdirectories subsequently
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects/$ https://data.cyverse.org/dav/{{ _irods_zone_name }}/projects/ [P,L]

              # Other projects directories should be permanantly redirected to data.cyverse.org
              RewriteRule ^/dav/{{ _irods_zone_name }}/projects/(.*)$ https://data.cyverse.org/dav/{{ _irods_zone_name }}/projects/$1 [R=308,L]
            comment: The WebDAV host

        apache_vhosts_ssl:
          - servername: "{{ _canonical_hostname }}"
            certificate_file: "{{ _webdav_tls_cert_file }}"
            certificate_key_file: "{{ _webdav_tls_key_file }}"
            certificate_chain_file: "{{ _webdav_tls_chain_file }}"
            extra_parameters: |
              #ServerAlias {{ inventory_hostname }}

              ErrorLog logs/https_error_log
              CustomLog logs/https_request_log {{ '"%{%Y-%m-%d %T}t.%{usec_frac}t %{SSL_PROTOCOL}x %{SSL_CIPHER}x %a \"%r\" %>s %L %{forensic-id}n"' }}
              LogLevel warn

              BrowserMatch "MSIE [2-5]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0

              <If "%{HTTP:Range} == 'bytes=0-'">
                # Remove the range header if requesting the whole file so that the response will
                # still be cached.
                RequestHeader unset Range
              </If>
              <Elseif "-n %{HTTP:Range}">
                # To prevent davrods from crashing, tell it not to cache partial responses
                # When varnish-cache is configured, this should be commented out for caching
                # RequestHeader merge Cache-Control no-store
              </Elseif>

              ProxyPass / http://127.0.0.1/ retry=0 timeout=300
              ProxyHTMLURLMap ^http: https: [R]

              Header edit Location ^http: https:
              Header merge Cache-Control public

              # Disable cache when varnish-cache is configured
              CacheDisable /

              ExpiresActive On

              <Files ~ "\.(cgi|shtml|phtml|php3?)$">
                SSLOptions +StdEnvVars
              </Files>

              <Directory "/var/www/cgi-bin">
                SSLOptions +StdEnvVars
              </Directory>
            comment: >-
              This proxy handles TLS, corrects requests, enables caching, and anonymous access for 
              XMLHttpRequests
        apache_vhosts_template: ../../templates/webdav/etc/httpd/conf.d/vhosts.conf.j2

  pre_tasks:
    - name: enable notifcations
      set_fact:
        notifications_enabled: true

    - name: package_facts uses auto, setup for next task
      package_facts:

    - name: build & install mod_ssl-rm_ssl_conf RPM package to remove ssl.conf
      include_tasks: tasks/install_rm_sslconf_rpm.yml
      when: "'mod_ssl-rm_ssl_conf' not in ansible_facts.packages"
      
    - name: install apache modules
      package:
        name: 
          - mod_proxy_html
          - mod_ssl
          - mod_ldap

    - name: update apache modules
      copy:
        src: "{{ item }}"
        dest: /etc/httpd/conf.modules.d
      with_fileglob:
        - 'files/webdav/etc/httpd/conf.modules.d/*'
      notify:
        - restart httpd

    - include_tasks: tasks/mk_webdav_dir_head.yml
      vars:
        head_dav_base: "{{ _irods_zone_name }}/{{ item.base }}"
        head_file: "{{ item.file }}"
      with_items:
        - file: home-head.html
          base: home
        - file: projects-head.html
          base: projects

    - include_tasks: tasks/install_webdav_html.yml
      vars:
        svc: dav

    - name: add root web page
      copy:
        src: files/webdav/var/www/html/index.html
        dest: /var/www/html/index.html

    - name: add robots.txt
      copy:
        src: files/webdav/var/www/html/robots.txt
        dest: /var/www/html/robots.txt

  post_tasks:
    - name: create apache systemd service dependencies directory
      file:
        path: /etc/systemd/system/httpd.service.requires
        state: directory

    - name: delete stale build dir for ldap-irods-auth package if exists
      file:
        path: /tmp/ldap_irods_auth_setup
        state: absent

    - name: check if ldap-irods-auth is already installed
      stat: 
        path: /usr/bin/ldap-irods-auth
      register: ldapirodsauthResp

    - name: check ldap-irods-auth version
      shell: /usr/bin/ldap-irods-auth -v | grep 'serviceVersion' | tr -d '",' | awk '{print $2}'
      register: ldapirodsauthVersion
      when: ldapirodsauthResp.stat.exists
      changed_when: false

    - name: check ldapirodsauth service account
      shell: id ldapirodsauth
      register: ldapirodsauthAccount
      failed_when: false
      changed_when: false

    - when: (not ldapirodsauthResp.stat.exists) or (ldapirodsauthAccount.rc != 0) or (ldapirodsauthVersion.stdout != 'v0.1.0')
      block:
        - name: check if ldap-irods-auth service exists
          stat: 
            path: /usr/lib/systemd/system/ldap-irods-auth.service
          register: serviceResp
          tags:
            - no_testing

        - name: stop ldap-irods-auth service if running
          service:
            name: ldap-irods-auth
            state: stopped
          when: serviceResp.stat.exists
          tags:
            - no_testing

        - name: create build dir for ldap-irods-auth package 
          file:
            path: /tmp/ldap_irods_auth_setup
            state: directory

        - name: download ldap-irods-auth package from github and uncompress
          unarchive:
            src: https://github.com/cyverse/ldap-irods-auth/archive/refs/heads/main.zip
            #src: https://github.com/cyverse/ldap-irods-auth/releases/download/v0.1.0/ldap_irods_auth_0.1.0.tar.gz
            dest: /tmp/ldap_irods_auth_setup
            remote_src: True
          register: unarchiveResp

        - name: install ldap-irods-auth service
          when: unarchiveResp is changed
          make: 
            chdir: /tmp/ldap_irods_auth_setup
            target: install_centos

        - name: delete build dir for ldap-irods-auth package
          file:
            path: /tmp/ldap_irods_auth_setup
            state: absent
    
    - name: configure ldap-irods-auth
      template:
        src: templates/webdav/etc/ldap-irods-auth/ldap-irods-auth.conf.j2
        dest: /etc/ldap-irods-auth/ldap-irods-auth.conf
        owner: ldapirodsauth
        mode: 0660
      notify:
        - restart ldap-irods-auth

    - name: setup ldap-irods-auth service
      copy:
        src: files/webdav/usr/lib/systemd/system/ldap-irods-auth.service
        dest: /usr/lib/systemd/system
      with_items:
        - ldap-irods-auth.service
      notify:
        - reload systemd
        - restart ldap-irods-auth

    - name: ensure ldap-irods-auth runs when varnish run
      file:
        path: /etc/systemd/system/varnish.service.requires/ldap-irods-auth.service
        src: /usr/lib/systemd/system/ldap-irods-auth.service
        state: link

    - name: open HTTP connection in firewall
      blockinfile:
        path: /etc/sysconfig/iptables
        insertbefore: -A INPUT -j REJECT
        marker: "# {mark} DS MANAGED BLOCK (webdav)"
        content: |
          {% for i in _webdav_allowed_src %}
          -A INPUT -m state --state NEW -p tcp -s {{ i }} --dport 80 -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ i }} --dport 8047 -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ i }} --dport 443 -j ACCEPT
          {% endfor %}
      notify: restart firewall

  handlers:
    - name: restart firewall
      when: notifications_enabled | default(false)
      service:
        name: iptables
        state: restarted

    - name: reload systemd
      when: notifications_enabled | default(false)
      systemd:
        daemon_reload: true

    - name: restart httpd
      when: notifications_enabled | default(false)
      service:
        name: httpd
        state: restarted
